# Generated by Django 4.2.7 on 2023-11-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_comment_blog_comment_content_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_parent', to='blogs.comment'),
        ),
    ]
