# Generated by Django 4.2.7 on 2023-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url_name',
            field=models.CharField(default='kjahsdlkfasd', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
