# Generated by Django 4.2.7 on 2023-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_url_name_alter_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='header',
            field=models.CharField(default='My Super Cool Blog', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
