# Generated by Django 4.2.7 on 2023-12-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
    ]
