# Generated by Django 4.2.7 on 2024-05-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_post_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CommentFlag_comment', to='blogs.comment')),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CommentFlag_comment', to='blogs.post')),
            ],
        ),
        migrations.DeleteModel(
            name='CommentFlag',
        ),
    ]
